package com.example.android.unscramble.ui.game


const val MAX_NO_OF_WORDS = 10
const val SCORE_INCREASE = 20

// List with all the words for the Game
val allWordsList: List<String> =
    listOf("hewan",
        "otomatis",
        "anekdot",
        "alfabet",
        "semua",
        "luar biasa",
        "bangkit",
        "balon",
        "keranjang",
        "bangku",
        "terbaik",
        "ulang tahun",
        "buku",
        "tas kerja",
        "kamera",
        "berkemah",
        "lilin",
        "kucing",
        "kembang kol",
        "obrolan",
        "anak-anak",
        "kelas",
        "klasik",
        "ruang kelas",
        "kopi",
        "berwarna",
        "kue",
        "kreatif",
        "berlayar",
        "menari",
        "siang",
        "dinosaurus",
        "gagang pintu",
        "makanan",
        "mimpi",
        "senja",
        "makan",
        "gajah",
        "zamrud",
        "menyeramkan",
        "listrik",
        "selesai",
        "bunga ",
        "ikuti",
        "rubah",
        "bingkai",
        "gratis",
        "sering",
        "corong",
        "hijau",
        "gitar",
        "toko kelontong",
        "kaca",
        "hebat",
        "tertawa kecil",
        "potongan rambut",
        "setengah",
        "buatan sendiri",
        "terjadi",
        "sayang",
        "cepat",
        "seratus",
        "es",
        "igloo",
        "investasi",
        "undangan",
        "ikon",
        "perkenalkan",
        "lelucon",
        "riang",
        "jurnal",
        "lompat",
        "bergabung",
        "kanguru",
        "papan ketik",
        "dapur",
        "koala",
        "baik",
        "kaleidoskop",
        "pemandangan",
        "terlambat",
        "tertawa",
        "belajar",
        "lemon",
        "surat",
        "bunga bakung",
        "majalah",
        "laut",
        "marshmallow",
        "labirin",
        "meditasi",
        "melodi",
        "menit",
        "monumen",
        "bulan",
        "sepeda motor",
        "gunung",
        "musik",
        "utara",
        "hidung",
        "malam",
        "nama",
        "tidak pernah",
        "bernegosiasi",
        "angka",
        "seberang",
        "gurita",
        "pohon ek",
        "pesanan",
        "buka",
        "kutub",
        "paket",
        "lukisan",
        "orang",
        "piknik",
        "bantal",
        "pizza",
        "podcast",
        "presentasi",
        "anak anjing",
        "teka-teki",
        "resep",
        "lepaskan",
        "restoran",
        "putar",
        "putar balik",
        "ruangan",
        "lari",
        "rahasia",
        "benih",
        "kapal",
        "baju",
        "seharusnya ",
        "kecil",
        "pesawat ruang angkasa",
        "melihat bintang",
        "keterampilan",
        "jalan",
        "gaya",
        "matahari terbit",
        "taksi",
        "rapi",
        "pengatur waktu",
        "bersama",
        "gigi",
        "turis",
        "perjalanan",
        "truk",
        "di bawah",
        "berguna",
        "unicorn",
        "unik",
        "mengangkat",
        "seragam",
        "vas",
        "biola",
        "pengunjung",
        "penglihatan",
        "volume",
        "pemandangan",
        "walrus",
        "mengembara",
        "dunia",
        "musim dingin",
        "sumur",
        "pusaran angin",
        "sinar-x",
        "gambang",
        "yoga",
        "yogurt",
        "yoyo",
        "kamu",
        "tahun",
        "enak",
        "zebra",
        "zigzag",
        "zoologi",
        "zona",
        "semangat")